package com.payline.payment.sandbox.utils;

import java.math.BigInteger;

public enum MagicAmountEnumValue {

    UNKNOWN_VALUE("", "", new BigInteger("-1")),

    // PAYMENT SERVICE RESPONSE
    PAYMENT_SERVICE__PAYMENT_RESPONSE_REDIRECT__10000 ("PAYMENT_SERVICE", "PAYMENT_RESPONSE_REDIRECT", new BigInteger("10000")),
    PAYMENT_SERVICE__PAYMENT_RESPONSE_REDIRECT__10001 ("PAYMENT_SERVICE", "PAYMENT_RESPONSE_REDIRECT", new BigInteger("10001")),
    PAYMENT_SERVICE__PAYMENT_RESPONSE_REDIRECT__10002 ("PAYMENT_SERVICE", "PAYMENT_RESPONSE_REDIRECT", new BigInteger("10002")),

    PAYMENT_SERVICE__PAYMENT_RESPONSE_FORM_UPDATED__10003 ("PAYMENT_SERVICE", "PAYMENT_RESPONSE_FORM_UPDATED", new BigInteger("10003")),
    PAYMENT_SERVICE__PAYMENT_RESPONSE_FORM_UPDATED__10004 ("PAYMENT_SERVICE", "PAYMENT_RESPONSE_FORM_UPDATED", new BigInteger("10004")),

    PAYMENT_SERVICE__PAYMENT_RESPONSE_DO_PAYMENT__10005 ("PAYMENT_SERVICE", "PAYMENT_RESPONSE_DO_PAYMENT", new BigInteger("10005")),

    PAYMENT_SERVICE__PAYMENT_RESPONSE_ACTIVE_WAITING__10006 ("PAYMENT_SERVICE", "PAYMENT_RESPONSE_ACTIVE_WAITING", new BigInteger("10006")),

    PAYMENT_SERVICE__PAYMENT_RESPONSE_SUCCESS__10007 ("PAYMENT_SERVICE", "PAYMENT_RESPONSE_SUCCESS", new BigInteger("10007")),

    PAYMENT_SERVICE__PAYMENT_RESPONSE_FAILURE__10090("PAYMENT_SERVICE", "PAYMENT_RESPONSE_FAILURE", new BigInteger("10090")),
    PAYMENT_SERVICE__PAYMENT_RESPONSE_FAILURE__10091 ("PAYMENT_SERVICE", "PAYMENT_RESPONSE_FAILURE", new BigInteger("10091")),

    PAYMENT_SERVICE__PAYMENT_RESPONSE_GENERIC_ERROR__10098 ("PAYMENT_SERVICE", "PAYMENT_RESPONSE_GENERIC_ERROR", new BigInteger("10098")),
    PAYMENT_SERVICE__PAYMENT_RESPONSE_GENERIC_ERROR__10099 ("PAYMENT_SERVICE", "PAYMENT_RESPONSE_GENERIC_ERROR", new BigInteger("10099")),

    // PAYMENT WITH REDIRECTION SERVICE
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_ON_HOLD__20000("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_ON_HOLD", new BigInteger("20000")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_ON_HOLD__20001("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_ON_HOLD", new BigInteger("20001")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_ON_HOLD__20002("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_ON_HOLD", new BigInteger("20002")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_ON_HOLD__20100("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_ON_HOLD", new BigInteger("20100")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_ON_HOLD__20101("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_ON_HOLD", new BigInteger("20101")),

    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_DO_PAYMENT__20003("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_DO_PAYMENT", new BigInteger("20003")),

    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_SUCCESS_20004("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_SUCCESS", new BigInteger("20004")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_SUCCESS_20005("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_SUCCESS", new BigInteger("20005")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_SUCCESS_20006("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_SUCCESS", new BigInteger("20006")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_SUCCESS_20007("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_SUCCESS", new BigInteger("20007")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_SUCCESS_20104("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_SUCCESS", new BigInteger("20104")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_SUCCESS_20105("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_SUCCESS", new BigInteger("20105")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_SUCCESS_20106("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_SUCCESS", new BigInteger("20106")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_SUCCESS_20107("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_SUCCESS", new BigInteger("20107")),

    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_FAILURE_20090("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_FAILURE", new BigInteger("20090")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_FAILURE_20091("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_FAILURE", new BigInteger("20091")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_FAILURE_20092("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_FAILURE", new BigInteger("20092")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_FAILURE_20190("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_FAILURE", new BigInteger("20190")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_FAILURE_20192("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_FAILURE", new BigInteger("20192")),

    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_GENERIC_ERROR__20098 ("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_GENERIC_ERROR", new BigInteger("20098")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_GENERIC_ERROR__20099 ("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_GENERIC_ERROR", new BigInteger("20099")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_GENERIC_ERROR__20198 ("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_GENERIC_ERROR", new BigInteger("20198")),
    PAYMENT_WITH_REDIRECTION_SERVICE__PAYMENT_RESPONSE_GENERIC_ERROR__20199 ("PAYMENT_WITH_REDIRECTION_SERVICE", "PAYMENT_RESPONSE_GENERIC_ERROR", new BigInteger("20199")),

    // PAYMENT FORM CONFIGURATION SERVICE
    PAYMENT_FORM_CONFIGURATION_SERVICE__PAYMENT_FORM_CONFIGURATION_RESPONSE_SPECIFIC_30000("PAYMENT_FORM_CONFIGURATION_SERVICE", "PAYMENT_FORM_CONFIGURATION_RESPONSE_SPECIFIC", new BigInteger("30000")),
    PAYMENT_FORM_CONFIGURATION_SERVICE__PAYMENT_FORM_CONFIGURATION_RESPONSE_SPECIFIC_30001("PAYMENT_FORM_CONFIGURATION_SERVICE", "PAYMENT_FORM_CONFIGURATION_RESPONSE_SPECIFIC", new BigInteger("30001")),

    PAYMENT_FORM_CONFIGURATION_SERVICE__PAYMENT_RESPONSE_FAILURE_30090("PAYMENT_FORM_CONFIGURATION_SERVICE", "PAYMENT_RESPONSE_FAILURE", new BigInteger("30090")),
    PAYMENT_FORM_CONFIGURATION_SERVICE__PAYMENT_RESPONSE_FAILURE_30091("PAYMENT_FORM_CONFIGURATION_SERVICE", "PAYMENT_RESPONSE_FAILURE", new BigInteger("30091")),

    // NOTIFICATION SERVICE
    NOTIFICATION_SERVICE__IGNORE_NOTIFICATION_RESPONSE_40000("NOTIFICATION_SERVICE", "IGNORE_NOTIFICATION_RESPONSE", new BigInteger("40000")),
    NOTIFICATION_SERVICE__IGNORE_NOTIFICATION_RESPONSE_40001("NOTIFICATION_SERVICE", "IGNORE_NOTIFICATION_RESPONSE", new BigInteger("40001")),

    NOTIFICATION_SERVICE__PAYMENT_RESPONSE_BY_NOTIFICATION_RESPONSE_40002("NOTIFICATION_SERVICE", "PAYMENT_RESPONSE_BY_NOTIFICATION_RESPONSE", new BigInteger("40002")),
    NOTIFICATION_SERVICE__PAYMENT_RESPONSE_BY_NOTIFICATION_RESPONSE_40003("NOTIFICATION_SERVICE", "PAYMENT_RESPONSE_BY_NOTIFICATION_RESPONSE", new BigInteger("40003")),

    NOTIFICATION_SERVICE__TRANSACTION_STATE_CHANGED_RESPONSE_40004("NOTIFICATION_SERVICE", "TRANSACTION_STATE_CHANGED_RESPONSE", new BigInteger("40004")),
    NOTIFICATION_SERVICE__TRANSACTION_STATE_CHANGED_RESPONSE_40005("NOTIFICATION_SERVICE", "TRANSACTION_STATE_CHANGED_RESPONSE", new BigInteger("40005")),

    NOTIFICATION_SERVICE__NOTIFICATION_RESPONSE_GENERIC_ERROR__40098("NOTIFICATION_SERVICE", "NOTIFICATION_RESPONSE_GENERIC_ERROR", new BigInteger("40098")),
    NOTIFICATION_SERVICE__NOTIFICATION_RESPONSE_GENERIC_ERROR__40099("NOTIFICATION_SERVICE", "NOTIFICATION_RESPONSE_GENERIC_ERROR", new BigInteger("40099")),

    // CAPTURE SERVICE
    CAPTURE_SERVICE__CAPTURE_RESPONSE_SUCCESS_50000("CAPTURE_SERVICE", "CAPTURE_RESPONSE_SUCCESS", new BigInteger("50000")),

    CAPTURE_SERVICE__CAPTURE_RESPONSE_FAILURE_50090("CAPTURE_SERVICE", "CAPTURE_RESPONSE_FAILURE", new BigInteger("50090")),

    CAPTURE_SERVICE__CAPTURE_RESPONSE_GENERIC_ERROR__50098("CAPTURE_SERVICE", "CAPTURE_RESPONSE_GENERIC_ERROR", new BigInteger("50098")),
    CAPTURE_SERVICE__CAPTURE_RESPONSE_GENERIC_ERROR__50099("CAPTURE_SERVICE", "CAPTURE_RESPONSE_GENERIC_ERROR", new BigInteger("50099")),

    // RESET SERVICE
    RESET_SERVICE__RESET_RESPONSE_FAILURE_60000("RESET_SERVICE", "RESET_RESPONSE_SUCCESS", new BigInteger("60000")),

    RESET_SERVICE__RESET_RESPONSE_SUCCESS_60090("RESET_SERVICE", "RESET_RESPONSE_FAILURE", new BigInteger("60090")),
    RESET_SERVICE__RESET_RESPONSE_SUCCESS_60091("RESET_SERVICE", "RESET_RESPONSE_FAILURE", new BigInteger("60091")),

    RESET_SERVICE__RESET_RESPONSE_GENERIC_ERROR_60098("RESET_SERVICE", "RESET_RESPONSE_GENERIC_ERROR", new BigInteger("60098")),
    RESET_SERVICE__RESET_RESPONSE_GENERIC_ERROR_60099("RESET_SERVICE", "RESET_RESPONSE_GENERIC_ERROR", new BigInteger("60099")),


    // REFUND SERVICE
    REFUND_SERVICE__REFUND_RESPONSE_SUCCESS_70000("REFUND_SERVICE", "REFUND_RESPONSE_SUCCESS", new BigInteger("70000")),

    RESET_SERVICE__REFUND_RESPONSE_SUCCESS_70090("REFUND_SERVICE", "REFUND_RESPONSE_FAILURE", new BigInteger("70090")),
    RESET_SERVICE__REFUND_RESPONSE_SUCCESS_70091("REFUND_SERVICE", "REFUND_RESPONSE_FAILURE", new BigInteger("70091")),

    REFUND_SERVICE__REFUND_RESPONSE_GENERIC_ERROR_70098("REFUND_SERVICE", "REFUND_RESPONSE_GENERIC_ERROR", new BigInteger("70098")),
    REFUND_SERVICE__REFUND_RESPONSE_GENERIC_ERROR_70099("REFUND_SERVICE", "REFUND_RESPONSE_GENERIC_ERROR", new BigInteger("70099"));


    private String service;
    private String response;
    private BigInteger amount;

    MagicAmountEnumValue(String service, String response, BigInteger amount) {
        this.service = service;
        this.response = response;
        this.amount = amount;
    }

    public String getService() {
        return service;
    }

    public String getResponse() {
        return response;
    }

    public BigInteger getAmount() {
        return amount;
    }


    public static MagicAmountEnumValue fromAmountValue(BigInteger amount) {

        for (MagicAmountEnumValue result : MagicAmountEnumValue.values()) {
            if (result.getAmount().equals(amount)) {
                return result;
            }
        }

        return MagicAmountEnumValue.UNKNOWN_VALUE;
    }

}